### ISSUE TITLE
Receive ": No such file or directory" when invoke piglow from command line

### ISSUE THREAD

**Issue by thisdavej** [seriousManual/node-piglow-cli#3]
I am not able to invoke `piglow` from the command line in Raspbian.

Example: `piglow --leg_0 100`

Leveraging [this StackOverflow answer](http://stackoverflow.com/a/27332494), I converted `bin/piglow.js` from CRLF to LF and it now works!

**Comment by seriousManual** [comment]
hi,
thank you for the heads up!
i republished the module with changed line endings (2.0.1)!

**Comment by thisdavej** [comment]
Awesome - thanks Manuel!  I'm planning to use node-piglow and node-piglow-cli in a couple future Node.js IoT tutorials I am developing for [thisDaveJ.com](http://thisdavej.com), and getting this error fixed helps ensure everything works as expected.

**Comment by seriousManual** [comment]
sounds great, would be nice if you could drop me a link when your tutorials are finished!

**Comment by thisdavej** [comment]
Absolutely - will do, Manuel.  I have a few other tutorials in the queue leading up to the piglow tutorials so it will probably be 2-3 months, but I'll let you know!
